/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Search } from "./Search";
import { SearchCountArgs } from "./SearchCountArgs";
import { SearchFindManyArgs } from "./SearchFindManyArgs";
import { SearchFindUniqueArgs } from "./SearchFindUniqueArgs";
import { CreateSearchArgs } from "./CreateSearchArgs";
import { UpdateSearchArgs } from "./UpdateSearchArgs";
import { DeleteSearchArgs } from "./DeleteSearchArgs";
import { User } from "../../user/base/User";
import { SearchService } from "../search.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Search)
export class SearchResolverBase {
  constructor(
    protected readonly service: SearchService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Search",
    action: "read",
    possession: "any",
  })
  async _searchesMeta(
    @graphql.Args() args: SearchCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Search])
  @nestAccessControl.UseRoles({
    resource: "Search",
    action: "read",
    possession: "any",
  })
  async searches(@graphql.Args() args: SearchFindManyArgs): Promise<Search[]> {
    return this.service.searches(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Search, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Search",
    action: "read",
    possession: "own",
  })
  async search(
    @graphql.Args() args: SearchFindUniqueArgs
  ): Promise<Search | null> {
    const result = await this.service.search(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Search)
  @nestAccessControl.UseRoles({
    resource: "Search",
    action: "create",
    possession: "any",
  })
  async createSearch(@graphql.Args() args: CreateSearchArgs): Promise<Search> {
    return await this.service.createSearch({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Search)
  @nestAccessControl.UseRoles({
    resource: "Search",
    action: "update",
    possession: "any",
  })
  async updateSearch(
    @graphql.Args() args: UpdateSearchArgs
  ): Promise<Search | null> {
    try {
      return await this.service.updateSearch({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Search)
  @nestAccessControl.UseRoles({
    resource: "Search",
    action: "delete",
    possession: "any",
  })
  async deleteSearch(
    @graphql.Args() args: DeleteSearchArgs
  ): Promise<Search | null> {
    try {
      return await this.service.deleteSearch(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Search): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
